ARG ODOO_VERSION

FROM odoo:${ODOO_VERSION}

USER root

RUN apt-get update && \
	apt-get install -y netcat-openbsd \
			wget

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir --break-system-packages -r /requirements.txt

CMD /usr/bin/python3 -m debugpy --listen 0.0.0.0:8070 /usr/bin/odoo -c /etc/odoo/odoo.conf